# Site settings
title: Edith Puclla
description: "Business Card Page"
url: "https://edithturn.github.io"
baseurl: ""
profilepic: "/images/edithpuclla.jpg"
bkimage: "/images/bk1.jpg"
google_analytics: UA-XXXXXX-X
#font_awesome: "XXXXXXXXXX.js"

author:
  name: "Edith Puclla"
  email: edithpuclla20@gmail.com
  twitter_username: edithpuclla
  github_username: edithturn
  linkedin_username: edithpuclla
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ["README.md", "screenshot-overview.png"]
